### ISSUE TITLE
Support for socket.io library

### ISSUE THREAD

**Issue by johnhigginsavila** [mayajs/socket#1]
## 📝 Description
A lot of projects relies on socket.io for realtime communications, can we add a wrapper to support socket.io?

## 📋 Todo:

- [ ] Add a socket.io wrapper and necessary dependencies
- [ ] Add unit testing
- [ ] Update documentation for socket.io wrapper
